### ISSUE TITLE
Pro : notification reçues en doubles 

### ISSUE THREAD

**Issue by lafrenchydev** [gitaroban/.github#2]
### Où cela est-il arrivé ? En Production, Recette ou Développement ?

Recette

### Utilisateur

La casa de phili

### Description du bug

L’app pro reçoit les notifications push en doubles ( dépôt avis, réservations…) 

![IMG_5577](https://github.com/gitaroban/.github/assets/133343889/d1a60e3c-d161-48ef-967e-6b504bf5071e)

### Etapes pour reproduire

1. faire une resa avec le conso, et le pro reçoit 2 notifs

**Comment by atournayre** [comment]
Clôturée car pas enregistrée au bon endroit => https://github.com/gitaroban/lafrenchy-issues/issues/349
