### ISSUE TITLE
Prod app pro : impossible de publier un événement 

### ISSUE THREAD

**Issue by lafrenchydev** [gitaroban/.github#3]
### Où cela est-il arrivé ? En Production, Recette ou Développement ?

Production

### Utilisateur

Chez la frenchy

### Description du bug

Lorsque je publie un événement il indique erreur de serveur 
![IMG_5595](https://github.com/gitaroban/.github/assets/133343889/20f8c545-46b7-4603-b4f3-6e50577fcbfe)

### Etapes pour reproduire

Publier un événement

**Comment by atournayre** [comment]
Déplacée vers gitaroban/lafrenchy-issues#351
