### ISSUE TITLE
Pro : impossible de publier une Java 

### ISSUE THREAD

**Issue by lafrenchydev** [gitaroban/.github#4]
### Où cela est-il arrivé ? En Production, Recette ou Développement ?

Production

### Utilisateur

Chez la frenchy 

### Description du bug

Lorsque le pro veut publier une Java un message d’erreur apparaît à la publication. 
![Uploading IMG_5596.png…]()

### Etapes pour reproduire

1. Prendre une photo 
2. Publication impossible

**Comment by atournayre** [comment]
Déplacée vers gitaroban/lafrenchy-issues#352
