### ISSUE TITLE
Conso : le pro n’a pas accepté la Java et elle s’est publié toute seule et en double 

### ISSUE THREAD

**Issue by lafrenchydev** [gitaroban/.github#5]
### Où cela est-il arrivé ? En Production, Recette ou Développement ?

Production

### Utilisateur

Philippine chevalier conso / chez LaFrenchy pro 

### Description du bug

1. Philippine en conso a pris une Java et l’a envoyé à chez la frenchy pour être publié mais elle s’est publié toute seule 
2. Sur l’appli pro : le nom de la personne qui l’a publié est «  À » et sur l’appli conso le nom est « p.chevalier »
![IMG_5598](https://github.com/gitaroban/.github/assets/133343889/4b483814-bedb-4102-8838-3d171c4696f0)
![IMG_5597](https://github.com/gitaroban/.github/assets/133343889/9c9dfd53-b504-48db-badf-c914d6c2fbc9)

### Etapes pour reproduire

![Uploading IMG_5599.png…]()

**Comment by atournayre** [comment]
Déplacée vers gitaroban/lafrenchy-issues#353
