### ISSUE TITLE
Conso : sur la Java plus rien ne s’affiche à part la photo 

### ISSUE THREAD

**Issue by lafrenchydev** [gitaroban/.github#6]
### Où cela est-il arrivé ? En Production, Recette ou Développement ?

Production

### Utilisateur

Philippine chevalier 

### Description du bug

Sur la Java , ni le temps, ni l’utilisateur, ni le nb de commères, ni partager ne s’affiche 
![IMG_5600](https://github.com/gitaroban/.github/assets/133343889/ec944e04-03b3-4031-ba8b-bfe85d67c548)

### Etapes pour reproduire

1  visionner une Java sur l’app Conso

**Comment by atournayre** [comment]
Déplacée vers gitaroban/lafrenchy-issues#350
