### ISSUE TITLE
[BUG]: placement forfait 3 : les demandes sont faites pour être placés au bar mais le bonhomme rose les Compte dans tout les produits ( vip, bar,fosse) 

### ISSUE THREAD

**Issue by lafrenchydev** [gitaroban/.github#8]
### Où cela est-il arrivé ? En Production, Recette ou Développement ?

Recette

### Utilisateur

La commanderie 

### Description du bug

- dans réservations s’affichent toutes les réservations confirmées 
- Les différents produits ouvert à la réservations sont donc selectionnables ( bar et fosse)
- or, le bonhomme rose compte 20 pers dans chaque produit alors qu’il ne devrait le compter que dans le produit choisi par le client ( soit 20 pers au bar)
![IMG_5797](https://github.com/gitaroban/.github/assets/133343889/cc79f6f6-dbfd-43e3-8f9f-afa3ead3482d)
![IMG_5796](https://github.com/gitaroban/.github/assets/133343889/2defa466-1642-4b5d-9468-dff6513d7ef5)
![IMG_5795](https://github.com/gitaroban/.github/assets/133343889/d6d43cd1-7c48-46a8-9b01-b8cae6a75ec1)
 

### Etapes pour reproduire

J

**Comment by raphhiessler** [comment]
@lafrenchydev c'est effectivement le comportement qui était convenu dans notre échange : "pour le jour consulté, toutes zones et services confondus"

![screenshot_email_jauge](https://github.com/gitaroban/.github/assets/2247063/2ca4aed1-d772-49b8-a8e4-c56b4f64f44c)

**Comment by lafrenchydev** [comment]
De ce fait ni le vert / ni le rose ne fonctionne ![image](https://github.com/gitaroban/.github/assets/133343889/315ee821-4277-4c67-97ba-a5196c20b8e0)
