### ISSUE TITLE
[BUG]: je ne peut pas réserver en fosse si le bar est plein 

### ISSUE THREAD

**Issue by lafrenchydev** [gitaroban/.github#9]
### Où cela est-il arrivé ? En Production, Recette ou Développement ?

Recette

### Utilisateur

La commanderie 

### Description du bug

Impossible de réserver dans la fosse alors qu’il n’y aucune réservation , mais le bar est plein 

### Etapes pour reproduire

1. Réserver dans le fosse ( capacité max 10pers) , or aucune place de réserver 
2. Créneau du bar à 18h plein, et si je réserve en fosse à 18h il me dit que c’est impossible 
3. La fosse est pourtant vide (il ne propose même pas d’être en liste d’attente 
4. Pour le pro c’est pareil impossible de réserver en fosse pour 18h 
![IMG_5794](https://github.com/gitaroban/.github/assets/133343889/528c0aea-17fd-4016-8c5e-0a752cda4a02)
![IMG_5798](https://github.com/gitaroban/.github/assets/133343889/6069ca4d-b1d8-4236-979b-48dd78f313d3)

**Comment by atournayre** [comment]
Le comportement remonté est normal.

![](https://github.com/gitaroban/.github/assets/4262077/2145864d-4389-4a88-baf2-6f0f935d6516)

![](https://github.com/gitaroban/.github/assets/4262077/707f4ac6-f58a-409d-a623-147f41b85542)
